// Auto-generated by LibreLane
module spi_slave(
`ifdef USE_POWER_PINS
  inout VSS,
  inout VDD,
`endif
  input clk,
  input rst_n,
  input sclk,
  input mosi,
  output miso,
  input cs_n
);
endmodule
